import wwebjs from 'whatsapp-web.js';
import type { Client, Message } from 'whatsapp-web.js';
const { LocalAuth } = wwebjs;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const WWebClient = (wwebjs as any).Client as typeof Client;
import * as QRCode from 'qrcode';
import { AuditLedger } from '../audit/auditLedger';

export type WhatsAppWebSessionState =
  | 'NOT_CONNECTED'
  | 'STARTING'
  | 'QR_REQUIRED'
  | 'AUTHENTICATING'
  | 'CONNECTED'
  | 'DISCONNECTED'
  | 'SESSION_EXPIRED'
  | 'BROWSER_ERROR'
  | 'CONNECTION_ERROR'
  | 'STOPPED';

export interface WhatsAppWebSessionMetadata {
  connectionId: string;
  provider: 'whatsapp_web';
  environment: 'development';
  status: WhatsAppWebSessionState;
  /** Real, scannable QR code as a data: URL image. Regenerated by whatsapp-web.js roughly every ~20s until scanned. */
  qrCodeDataUrl?: string;
  connectedAt?: string;
  lastSeenAt?: string;
  accountName?: string;
  maskedPhone?: string;
  errorMessage?: string;
}

export type InboundMessageHandler = (fromPhone: string, text: string, rawMessageId: string) => void;

/**
 * Section 8-10, 55: Real WhatsApp Web session, isolated from the AI layer.
 * The AI never touches `client`, `pupPage`, `pupBrowser`, or the LocalAuth
 * session directory (.wwebjs_auth/) - only this module does. Everything the
 * rest of the app sees comes from getSafeMetadataForAI()/getSessionMetadata(),
 * which never include browser/session internals.
 */
export class WhatsAppWebSessionManager {
  private static client: Client | null = null;

  private static metadata: WhatsAppWebSessionMetadata = {
    connectionId: 'wa-web-session-dev-01',
    provider: 'whatsapp_web',
    environment: 'development',
    status: 'NOT_CONNECTED',
  };

  private static inboundHandlers: InboundMessageHandler[] = [];

  public static onInboundMessage(handler: InboundMessageHandler): void {
    this.inboundHandlers.push(handler);
  }

  /**
   * Section 2 & 55: SECURITY RULE
   * AI agents receive ZERO access to cookies, session tokens, browser profiles, or auth credentials.
   */
  public static getSafeMetadataForAI(): {
    status: WhatsAppWebSessionState;
    connected: boolean;
    provider: string;
    environment: string;
  } {
    return {
      status: this.metadata.status,
      connected: this.metadata.status === 'CONNECTED',
      provider: 'whatsapp_web',
      environment: 'development',
    };
  }

  public static getSessionMetadata(): WhatsAppWebSessionMetadata {
    return { ...this.metadata };
  }

  /**
   * Launches (or re-attaches to) a real WhatsApp Web browser session.
   * Idempotent: calling this while already STARTING/QR_REQUIRED/CONNECTED
   * just returns current state rather than spawning a second browser.
   */
  public static startSession(adminUserId: string = 'sys-admin'): WhatsAppWebSessionMetadata {
    if (this.client && ['STARTING', 'QR_REQUIRED', 'AUTHENTICATING', 'CONNECTED'].includes(this.metadata.status)) {
      return { ...this.metadata };
    }

    this.metadata = {
      ...this.metadata,
      status: 'STARTING',
      qrCodeDataUrl: undefined,
      errorMessage: undefined,
      lastSeenAt: new Date().toISOString(),
    };

    AuditLedger.logOperationalEvent(
      adminUserId,
      'ADMIN',
      'START_WHATSAPP_WEB_SESSION',
      'SESSION:WA_WEB',
      'Launched isolated WhatsApp Web browser session (whatsapp-web.js).'
    );

    const client = new WWebClient({
      authStrategy: new LocalAuth({ clientId: 'agritrust-dev' }),
      puppeteer: {
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      },
    });

    client.on('qr', async (qr: string) => {
      try {
        const qrCodeDataUrl = await QRCode.toDataURL(qr);
        this.metadata = {
          ...this.metadata,
          status: 'QR_REQUIRED',
          qrCodeDataUrl,
          lastSeenAt: new Date().toISOString(),
        };
      } catch (err) {
        this.metadata = {
          ...this.metadata,
          status: 'BROWSER_ERROR',
          errorMessage: `Failed to render QR code: ${err instanceof Error ? err.message : String(err)}`,
        };
      }
    });

    client.on('authenticated', () => {
      this.metadata = {
        ...this.metadata,
        status: 'AUTHENTICATING',
        qrCodeDataUrl: undefined,
        lastSeenAt: new Date().toISOString(),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'AUTHENTICATE_WHATSAPP_WEB_SUCCESS',
        'SESSION:WA_WEB',
        'WhatsApp Web session authenticated by phone QR scan.'
      );
    });

    client.on('auth_failure', (msg: string) => {
      this.metadata = {
        ...this.metadata,
        status: 'CONNECTION_ERROR',
        errorMessage: `Authentication failed: ${msg}`,
      };
      AuditLedger.logImmutableSecurityEvent(
        adminUserId,
        'WHATSAPP_WEB_AUTH_FAILURE',
        'MEDIUM',
        `WhatsApp Web authentication failed: ${msg}`
      );
    });

    client.on('ready', () => {
      const info = client.info;
      const accountName = info?.pushname || 'Connected WhatsApp Account';
      const rawPhone = info?.wid?.user || '';
      const maskedPhone = rawPhone
        ? `+${rawPhone.slice(0, Math.max(0, rawPhone.length - 4))}XXXX`
        : undefined;

      this.metadata = {
        ...this.metadata,
        status: 'CONNECTED',
        accountName,
        maskedPhone,
        connectedAt: new Date().toISOString(),
        lastSeenAt: new Date().toISOString(),
        qrCodeDataUrl: undefined,
      };

      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_READY',
        `ACCOUNT:${accountName}`,
        `WhatsApp Web session is CONNECTED and ready to send/receive real messages (masked phone: ${maskedPhone}).`
      );
    });

    client.on('disconnected', (reason: string) => {
      this.metadata = {
        ...this.metadata,
        status: 'DISCONNECTED',
        qrCodeDataUrl: undefined,
        errorMessage: reason,
        lastSeenAt: new Date().toISOString(),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_DISCONNECTED',
        'SESSION:WA_WEB',
        `WhatsApp Web session disconnected: ${reason}`
      );
      this.client = null;
    });

    // Section 13-14: real inbound messages, forwarded to registered handlers.
    // The AI never sees this event directly - only the (fromPhone, text) pair
    // any handler is given, via the messaging gateway.
    client.on('message', (msg: Message) => {
      if (msg.fromMe) return;
      if (msg.from.endsWith('@g.us')) return; // ignore group chats
      if (msg.from === 'status@broadcast') return;
      if (msg.isStatus) return;

      const fromPhone = `+${msg.from.replace('@c.us', '')}`;
      const text = msg.body || '';
      this.metadata = { ...this.metadata, lastSeenAt: new Date().toISOString() };

      for (const handler of this.inboundHandlers) {
        try {
          handler(fromPhone, text, msg.id._serialized);
        } catch (err) {
          AuditLedger.logOperationalEvent(
            'sys-admin',
            'ADMIN',
            'WHATSAPP_WEB_INBOUND_HANDLER_ERROR',
            `SENDER:${fromPhone}`,
            `Inbound message handler threw: ${err instanceof Error ? err.message : String(err)}`
          );
        }
      }
    });

    client.initialize().catch((err: unknown) => {
      this.metadata = {
        ...this.metadata,
        status: 'BROWSER_ERROR',
        errorMessage: err instanceof Error ? err.message : String(err),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_INIT_FAILED',
        'SESSION:WA_WEB',
        `client.initialize() failed: ${err instanceof Error ? err.message : String(err)}`
      );
      this.client = null;
    });

    this.client = client;
    return { ...this.metadata };
  }

  /** Real send. Throws if not connected - caller (provider) is responsible for catching. */
  public static async sendRealMessage(toPhone: string, text: string): Promise<{ id: string }> {
    if (!this.client || this.metadata.status !== 'CONNECTED') {
      throw new Error(`WhatsApp Web session is not connected (status: ${this.metadata.status}).`);
    }
    const chatId = `${toPhone.replace(/[^0-9]/g, '')}@c.us`;
    const sent = await this.client.sendMessage(chatId, text);
    return { id: sent.id._serialized };
  }

  public static async disconnectSession(adminUserId: string = 'sys-admin'): Promise<WhatsAppWebSessionMetadata> {
    if (this.client) {
      try {
        await this.client.destroy();
      } catch {
        // best-effort; fall through to clear local state regardless
      }
      this.client = null;
    }

    this.metadata = {
      ...this.metadata,
      status: 'DISCONNECTED',
      qrCodeDataUrl: undefined,
      accountName: undefined,
      maskedPhone: undefined,
      lastSeenAt: new Date().toISOString(),
    };

    AuditLedger.logOperationalEvent(
      adminUserId,
      'ADMIN',
      'DISCONNECT_WHATSAPP_WEB',
      'SESSION:WA_WEB',
      'Terminated WhatsApp Web development browser session.'
    );

    return { ...this.metadata };
  }
}
