import wwebjs from 'whatsapp-web.js';
import type { Client, Message } from 'whatsapp-web.js';
const { LocalAuth } = wwebjs;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const WWebClient = (wwebjs as any).Client as typeof Client;
import * as QRCode from 'qrcode';
import { AuditLedger } from '../audit/auditLedger';

// Sync functions registered from server.ts so this file stays free of
// direct better-sqlite3 imports (which would re-enter the browser bundle)
export type SyncFunctions = {
  upsertChat: (c: any) => void;
  upsertContact: (c: any) => void;
  upsertMessage: (m: any) => void;
  upsertCallLog: (l: any) => void;
  getContacts: () => any[];
  getChats: () => any[];
  getMessages: (chatId: string, limit?: number, before?: number) => any[];
  getCallLogs: (limit?: number) => any[];
  markChatRead: (chatId: string) => void;
  getSyncStats: () => { chats: number; contacts: number; messages: number; calls: number };
  searchContacts: (q: string) => any[];
};
let _syncFns: SyncFunctions | null = null;
export function registerSyncFunctions(fns: SyncFunctions): void { _syncFns = fns; }
export function getSyncFunctions(): SyncFunctions | null { return _syncFns; }

export type WhatsAppWebSessionState =
  | 'NOT_CONNECTED'
  | 'STARTING'
  | 'QR_REQUIRED'
  | 'AUTHENTICATING'
  | 'CONNECTED'
  | 'DISCONNECTED'
  | 'SESSION_EXPIRED'
  | 'BROWSER_ERROR'
  | 'CONNECTION_ERROR'
  | 'STOPPED';

export interface WhatsAppWebSessionMetadata {
  connectionId: string;
  provider: 'whatsapp_web';
  environment: 'development';
  status: WhatsAppWebSessionState;
  /** Real, scannable QR code as a data: URL image. Regenerated by whatsapp-web.js roughly every ~20s until scanned. */
  qrCodeDataUrl?: string;
  connectedAt?: string;
  lastSeenAt?: string;
  accountName?: string;
  maskedPhone?: string;
  errorMessage?: string;
}

export type InboundMessageHandler = (fromPhone: string, text: string, rawMessageId: string) => void;

/**
 * Section 8-10, 55: Real WhatsApp Web session, isolated from the AI layer.
 * The AI never touches `client`, `pupPage`, `pupBrowser`, or the LocalAuth
 * session directory (.wwebjs_auth/) - only this module does. Everything the
 * rest of the app sees comes from getSafeMetadataForAI()/getSessionMetadata(),
 * which never include browser/session internals.
 */
export class WhatsAppWebSessionManager {
  private static client: Client | null = null;

  private static metadata: WhatsAppWebSessionMetadata = {
    connectionId: 'wa-web-session-dev-01',
    provider: 'whatsapp_web',
    environment: 'development',
    status: 'NOT_CONNECTED',
  };

  private static inboundHandlers: InboundMessageHandler[] = [];

  public static onInboundMessage(handler: InboundMessageHandler): void {
    this.inboundHandlers.push(handler);
  }

  /**
   * Section 2 & 55: SECURITY RULE
   * AI agents receive ZERO access to cookies, session tokens, browser profiles, or auth credentials.
   */
  public static getSafeMetadataForAI(): {
    status: WhatsAppWebSessionState;
    connected: boolean;
    provider: string;
    environment: string;
  } {
    return {
      status: this.metadata.status,
      connected: this.metadata.status === 'CONNECTED',
      provider: 'whatsapp_web',
      environment: 'development',
    };
  }

  public static getSessionMetadata(): WhatsAppWebSessionMetadata {
    return { ...this.metadata };
  }

  /**
   * Launches (or re-attaches to) a real WhatsApp Web browser session.
   * Idempotent: calling this while already STARTING/QR_REQUIRED/CONNECTED
   * just returns current state rather than spawning a second browser.
   */
  public static startSession(adminUserId: string = 'sys-admin'): WhatsAppWebSessionMetadata {
    if (this.client && ['STARTING', 'QR_REQUIRED', 'AUTHENTICATING', 'CONNECTED'].includes(this.metadata.status)) {
      return { ...this.metadata };
    }

    this.metadata = {
      ...this.metadata,
      status: 'STARTING',
      qrCodeDataUrl: undefined,
      errorMessage: undefined,
      lastSeenAt: new Date().toISOString(),
    };

    AuditLedger.logOperationalEvent(
      adminUserId,
      'ADMIN',
      'START_WHATSAPP_WEB_SESSION',
      'SESSION:WA_WEB',
      'Launched isolated WhatsApp Web browser session (whatsapp-web.js).'
    );

    const client = new WWebClient({
      authStrategy: new LocalAuth({ clientId: 'agritrust-dev' }),
      puppeteer: {
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      },
    });

    client.on('qr', async (qr: string) => {
      try {
        const qrCodeDataUrl = await QRCode.toDataURL(qr);
        this.metadata = {
          ...this.metadata,
          status: 'QR_REQUIRED',
          qrCodeDataUrl,
          lastSeenAt: new Date().toISOString(),
        };
      } catch (err) {
        this.metadata = {
          ...this.metadata,
          status: 'BROWSER_ERROR',
          errorMessage: `Failed to render QR code: ${err instanceof Error ? err.message : String(err)}`,
        };
      }
    });

    client.on('authenticated', () => {
      this.metadata = {
        ...this.metadata,
        status: 'AUTHENTICATING',
        qrCodeDataUrl: undefined,
        lastSeenAt: new Date().toISOString(),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'AUTHENTICATE_WHATSAPP_WEB_SUCCESS',
        'SESSION:WA_WEB',
        'WhatsApp Web session authenticated by phone QR scan.'
      );
    });

    client.on('auth_failure', (msg: string) => {
      this.metadata = {
        ...this.metadata,
        status: 'CONNECTION_ERROR',
        errorMessage: `Authentication failed: ${msg}`,
      };
      AuditLedger.logImmutableSecurityEvent(
        adminUserId,
        'WHATSAPP_WEB_AUTH_FAILURE',
        'MEDIUM',
        `WhatsApp Web authentication failed: ${msg}`
      );
    });

    client.on('ready', () => {
      const info = client.info;
      const accountName = info?.pushname || 'Connected WhatsApp Account';
      const rawPhone = info?.wid?.user || '';
      const maskedPhone = rawPhone
        ? `+${rawPhone.slice(0, Math.max(0, rawPhone.length - 4))}XXXX`
        : undefined;

      this.metadata = {
        ...this.metadata,
        status: 'CONNECTED',
        accountName,
        maskedPhone,
        connectedAt: new Date().toISOString(),
        lastSeenAt: new Date().toISOString(),
        qrCodeDataUrl: undefined,
      };

      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_READY',
        `ACCOUNT:${accountName}`,
        `WhatsApp Web session is CONNECTED and ready to send/receive real messages (masked phone: ${maskedPhone}).`
      );

      // Full sync runs in background after connection is established
      this.runFullSync(client).catch((err) => {
        AuditLedger.logOperationalEvent('sys-admin', 'ADMIN', 'WHATSAPP_WEB_SYNC_ERROR', 'SYNC', `Full sync failed: ${err?.message}`);
      });
    });

    client.on('disconnected', (reason: string) => {
      this.metadata = {
        ...this.metadata,
        status: 'DISCONNECTED',
        qrCodeDataUrl: undefined,
        errorMessage: reason,
        lastSeenAt: new Date().toISOString(),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_DISCONNECTED',
        'SESSION:WA_WEB',
        `WhatsApp Web session disconnected: ${reason}`
      );
      this.client = null;
    });

    // Real inbound messages: forward to AI pipeline AND store encrypted
    client.on('message', (msg: Message) => {
      if (msg.from === 'status@broadcast') return;
      if (msg.isStatus) return;

      const fromPhone = `+${msg.from.replace(/@c\.us|@g\.us/, '')}`;
      const text = msg.body || '';
      this.metadata = { ...this.metadata, lastSeenAt: new Date().toISOString() };

      // Store to encrypted DB
      const fns = getSyncFunctions();
      if (fns) {
        try {
          fns.upsertMessage({
            id: msg.id._serialized, chatId: msg.from, body: text,
            type: msg.type || 'chat', fromMe: !!msg.fromMe,
            fromPhone, fromName: (msg as any).notifyName || fromPhone,
            timestamp: msg.timestamp, hasMedia: !!msg.hasMedia,
            mediaMimeType: (msg as any).mimetype || undefined,
            isForwarded: !!(msg as any).isForwarded,
            isStarred: !!(msg as any).isStarred, ack: (msg as any).ack || 0,
          });
          // Update chat's last message
          fns.upsertChat({
            id: msg.from,
            name: (msg as any).notifyName || fromPhone,
            phone: fromPhone,
            isGroup: msg.from.endsWith('@g.us'),
            isArchived: false, isPinned: false, isMuted: false,
            unreadCount: 1, lastMessage: text,
            lastMessageType: msg.type || 'chat',
            lastMessageFromMe: !!msg.fromMe,
            timestamp: msg.timestamp,
          });
        } catch { /* non-fatal */ }
      }

      // Only forward 1:1 non-status messages to AI pipeline
      if (!msg.fromMe && !msg.from.endsWith('@g.us')) {
        for (const handler of this.inboundHandlers) {
          try {
            handler(fromPhone, text, msg.id._serialized);
          } catch (err) {
            AuditLedger.logOperationalEvent(
              'sys-admin', 'ADMIN', 'WHATSAPP_WEB_INBOUND_HANDLER_ERROR',
              `SENDER:${fromPhone}`,
              `Inbound handler threw: ${err instanceof Error ? err.message : String(err)}`
            );
          }
        }
      }
    });

    // Outgoing messages — store encrypted too
    client.on('message_create', (msg: Message) => {
      if (!msg.fromMe) return;
      const fns = getSyncFunctions();
      if (!fns) return;
      try {
        fns.upsertMessage({
          id: msg.id._serialized, chatId: msg.to || msg.from, body: msg.body || '',
          type: msg.type || 'chat', fromMe: true,
          fromPhone: 'me', fromName: 'Me',
          timestamp: msg.timestamp, hasMedia: !!msg.hasMedia,
          mediaMimeType: (msg as any).mimetype || undefined,
          isForwarded: false, isStarred: false, ack: (msg as any).ack || 1,
        });
      } catch { /* non-fatal */ }
    });

    // Call logs
    client.on('call', (call: any) => {
      const fns = getSyncFunctions();
      if (!fns) return;
      try {
        fns.upsertCallLog({
          id: call.id, fromPhone: call.from || '',
          fromName: '', fromMe: !!call.fromMe,
          isVideo: !!call.isVideo, isGroup: !!call.isGroup,
          timestamp: call.timestamp || Math.floor(Date.now() / 1000),
          durationSeconds: 0, status: 'incoming',
        });
      } catch { /* non-fatal */ }
    });

    client.initialize().catch((err: unknown) => {
      this.metadata = {
        ...this.metadata,
        status: 'BROWSER_ERROR',
        errorMessage: err instanceof Error ? err.message : String(err),
      };
      AuditLedger.logOperationalEvent(
        adminUserId,
        'ADMIN',
        'WHATSAPP_WEB_INIT_FAILED',
        'SESSION:WA_WEB',
        `client.initialize() failed: ${err instanceof Error ? err.message : String(err)}`
      );
      this.client = null;
    });

    this.client = client;
    return { ...this.metadata };
  }

  /** Syncs all chats, contacts and recent messages from the live session */
  public static async runFullSync(clientArg?: any): Promise<{ chats: number; contacts: number; messages: number }> {
    const c = clientArg || this.client;
    if (!c) throw new Error('Not connected');
    const fns = getSyncFunctions();
    if (!fns) throw new Error('Sync functions not registered');

    let chatCount = 0, contactCount = 0, msgCount = 0;

    // 1. Contacts
    try {
      const contacts = await c.getContacts();
      for (const contact of contacts) {
        if (!contact.id?.user) continue;
        let picUrl: string | undefined;
        try { picUrl = await contact.getProfilePicUrl(); } catch {}
        fns.upsertContact({
          id: contact.id._serialized, phone: contact.number || contact.id.user,
          name: contact.name, pushname: contact.pushname,
          shortName: contact.shortName, isBusiness: !!contact.isBusiness,
          isGroup: !!contact.isGroup, isMyContact: !!contact.isMyContact,
          isBlocked: !!contact.isBlocked, profilePicUrl: picUrl,
        });
        contactCount++;
      }
    } catch (err) { AuditLedger.logOperationalEvent('sys-admin', 'ADMIN', 'WA_SYNC_CONTACTS_ERROR', 'SYNC', String(err)); }

    // 2. Chats + recent messages
    try {
      const chats = await c.getChats();
      for (const chat of chats) {
        let picUrl: string | undefined;
        try { picUrl = await c.getProfilePicUrl(chat.id._serialized); } catch {}
        const lastMsg = chat.lastMessage;
        fns.upsertChat({
          id: chat.id._serialized, name: chat.name,
          phone: chat.id.user || '',
          isGroup: chat.isGroup, isArchived: chat.archived,
          isPinned: chat.pinned, isMuted: chat.isMuted,
          unreadCount: chat.unreadCount,
          lastMessage: lastMsg?.body || '',
          lastMessageType: lastMsg?.type || 'chat',
          lastMessageFromMe: !!(lastMsg?.fromMe),
          timestamp: chat.timestamp,
          profilePicUrl: picUrl,
        });
        chatCount++;

        // Fetch last 50 messages per chat
        try {
          const messages = await chat.fetchMessages({ limit: 50 });
          for (const msg of messages) {
            fns.upsertMessage({
              id: msg.id._serialized, chatId: chat.id._serialized,
              body: msg.body || '', type: msg.type || 'chat',
              fromMe: !!msg.fromMe, fromPhone: msg.from?.replace(/@c\.us|@g\.us/, '') || '',
              fromName: (msg as any).notifyName || '',
              timestamp: msg.timestamp, hasMedia: !!msg.hasMedia,
              mediaMimeType: (msg as any).mimetype || undefined,
              isForwarded: !!(msg as any).isForwarded,
              isStarred: !!(msg as any).isStarred,
              ack: (msg as any).ack || 0,
            });
            msgCount++;
          }
        } catch { /* Some chats may fail - continue */ }
      }
    } catch (err) { AuditLedger.logOperationalEvent('sys-admin', 'ADMIN', 'WA_SYNC_CHATS_ERROR', 'SYNC', String(err)); }

    AuditLedger.logOperationalEvent('sys-admin', 'ADMIN', 'WHATSAPP_WEB_FULL_SYNC_COMPLETE', 'SYNC',
      `Sync complete: ${chatCount} chats, ${contactCount} contacts, ${msgCount} messages`);

    return { chats: chatCount, contacts: contactCount, messages: msgCount };
  }

  /** Send a message to any phone number (starts new chat if needed) */
  public static async sendToPhone(toPhone: string, text: string): Promise<{ id: string }> {
    if (!this.client || this.metadata.status !== 'CONNECTED') {
      throw new Error(`Not connected (status: ${this.metadata.status})`);
    }
    const chatId = `${toPhone.replace(/[^0-9]/g, '')}@c.us`;
    const sent = await this.client.sendMessage(chatId, text);
    return { id: sent.id._serialized };
  }

  /** Real send. Throws if not connected - caller (provider) is responsible for catching. */
  public static async sendRealMessage(toPhone: string, text: string): Promise<{ id: string }> {
    if (!this.client || this.metadata.status !== 'CONNECTED') {
      throw new Error(`WhatsApp Web session is not connected (status: ${this.metadata.status}).`);
    }
    const chatId = `${toPhone.replace(/[^0-9]/g, '')}@c.us`;
    const sent = await this.client.sendMessage(chatId, text);
    return { id: sent.id._serialized };
  }

  public static async disconnectSession(adminUserId: string = 'sys-admin'): Promise<WhatsAppWebSessionMetadata> {
    if (this.client) {
      try {
        await this.client.destroy();
      } catch {
        // best-effort; fall through to clear local state regardless
      }
      this.client = null;
    }

    this.metadata = {
      ...this.metadata,
      status: 'DISCONNECTED',
      qrCodeDataUrl: undefined,
      accountName: undefined,
      maskedPhone: undefined,
      lastSeenAt: new Date().toISOString(),
    };

    AuditLedger.logOperationalEvent(
      adminUserId,
      'ADMIN',
      'DISCONNECT_WHATSAPP_WEB',
      'SESSION:WA_WEB',
      'Terminated WhatsApp Web development browser session.'
    );

    return { ...this.metadata };
  }
}
