import {
  User,
  FarmerProfile,
  BuyerProfile,
  Farm,
  Crop,
  Harvest,
  Lot,
  LotEvent,
  LotQuality,
  LotDocument,
  Product,
  Order,
  LogisticsOrder,
  Shipment,
  Invoice,
  ProcurementRequest,
  Settlement,
  SupplySubmission,
  CMSPageBlock,
  MarketingSubscriber,
  CMSSEOConfig,
  CMSNavigationItem,
  CMSFooterConfig,
  MediaAsset,
  AdminProfile,
  FeatureFlagSetting,
  ActiveSession,
  NotificationRecipientRouting,
  WhatsAppAccount,
  WhatsAppContact,
  WhatsAppConversation,
  WhatsAppMessage,
  WhatsAppTemplate,
  WhatsAppNegotiationPolicy,
  MarketplaceSettings,
} from './schema';

export const SEED_FARMER_USER: User = {
  id: 'usr-farmer-01',
  email: 'm.holder@holderproduce.test',
  name: 'Marcus Holder',
  role: 'FARMER',
  organisationId: 'org-farmer-01',
  createdAt: '2026-01-15T08:00:00Z',
  updatedAt: '2026-01-15T08:00:00Z',
};

export const SEED_FARMER_PROFILE: FarmerProfile = {
  id: 'fp-01',
  userId: 'usr-farmer-01',
  organisationId: 'org-farmer-01',
  businessName: 'Holder Agricultural Produce',
  contactName: 'Marcus Holder',
  privatePhone: '+1-555-019-4821',
  privateAddress: '742 Evergreen Valley Road, Plot 14',
  privateGpsLat: 13.1939,
  privateGpsLng: -59.5432,
  publicRegion: 'Western Agricultural Zone 4',
  trustScore: 98.4,
  verified: true,
  createdAt: '2026-01-15T08:30:00Z',
};

export const SEED_BUYER_USER: User = {
  id: 'usr-buyer-01',
  email: 'procurement@islandfresh.test',
  name: 'Sarah Jenkins',
  role: 'BUYER',
  organisationId: 'org-buyer-01',
  createdAt: '2026-02-01T09:00:00Z',
  updatedAt: '2026-02-01T09:00:00Z',
};

export const SEED_BUYER_PROFILE: BuyerProfile = {
  id: 'bp-01',
  userId: 'usr-buyer-01',
  organisationId: 'org-buyer-01',
  businessName: 'Island Fresh Hospitality Group',
  contactName: 'Sarah Jenkins',
  privatePhone: '+1-555-018-9920',
  privateAddress: '88 Harbour View Boulevard, Suite 400',
  creditLimit: 50000,
  verified: true,
  category: 'Hotels',
  deliveryLocations: ['Harbour View Resort', 'Downtown Grand Hotel'],
  paymentTerms: 'Net 30',
  orderHistoryCount: 14,
  createdAt: '2026-02-01T09:15:00Z',
};

export const SEED_BUYERS: BuyerProfile[] = [
  SEED_BUYER_PROFILE,
  {
    id: 'bp-02',
    userId: 'usr-buyer-02',
    organisationId: 'org-buyer-02',
    businessName: 'Coral Bay Hotel & Resort',
    contactName: 'David Miller',
    privatePhone: '+1-555-022-8811',
    privateAddress: '12 Beachfront Highway, St. James',
    creditLimit: 75000,
    verified: true,
    category: 'Hotels',
    deliveryLocations: ['Coral Bay Main Kitchen'],
    paymentTerms: 'Net 15',
    orderHistoryCount: 8,
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'bp-03',
    userId: 'usr-buyer-03',
    organisationId: 'org-buyer-03',
    businessName: 'Barbados Fresh Foods Distributor',
    contactName: 'Elena Rostova',
    privatePhone: '+1-555-033-7744',
    privateAddress: '45 Industrial Logistics Park, Warehouse 7',
    creditLimit: 120000,
    verified: true,
    category: 'Distributors',
    deliveryLocations: ['Central Distribution Hub', 'North Port Terminal'],
    paymentTerms: 'Net 45',
    orderHistoryCount: 22,
    createdAt: '2026-01-20T11:00:00Z',
  },
];

export const SEED_SELLERS: FarmerProfile[] = [
  {
    ...SEED_FARMER_PROFILE,
    category: 'Commercial Farm',
    primaryCrops: ['Tomatoes', 'Lettuce', 'Cucumbers', 'Peppers'],
    farmSizeHectares: 45,
    productionCapacityKg: 50000,
    certifications: ['GlobalGAP', 'Good Agricultural Practices (GAP)', 'Organic Certified'],
  },
  {
    id: 'fp-02',
    userId: 'usr-farmer-02',
    organisationId: 'org-farmer-02',
    businessName: 'Sunrise Agricultural Cooperative',
    contactName: 'Arthur Pendelton',
    privatePhone: '+1-555-044-3322',
    privateAddress: '88 Rural Valley Road',
    privateGpsLat: 13.221,
    privateGpsLng: -59.589,
    publicRegion: 'Eastern Agricultural Zone 2',
    trustScore: 96.2,
    verified: true,
    category: 'Cooperative',
    primaryCrops: ['Carrots', 'Sweet Potatoes', 'Peppers'],
    farmSizeHectares: 120,
    productionCapacityKg: 120000,
    certifications: ['FairTrade', 'GAP Certified'],
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'fp-03',
    userId: 'usr-farmer-03',
    organisationId: 'org-farmer-03',
    businessName: 'Island Harvest Hydroponics',
    contactName: 'Chloe Zhang',
    privatePhone: '+1-555-055-2211',
    privateAddress: '14 Tech Agriculture Way',
    privateGpsLat: 13.155,
    privateGpsLng: -59.612,
    publicRegion: 'Central Agricultural Zone 1',
    trustScore: 99.1,
    verified: true,
    category: 'Hydroponic Farm',
    primaryCrops: ['Lettuce', 'Herbs', 'Microgreens'],
    farmSizeHectares: 15,
    productionCapacityKg: 35000,
    certifications: ['HydroCert A+', 'Pesticide Free'],
    createdAt: '2026-02-05T14:00:00Z',
  },
];

export const SEED_SUPPLY_SUBMISSIONS: SupplySubmission[] = [
  {
    id: 'SUP-2026-000001',
    sellerId: 'fp-01',
    sellerName: 'Green Valley Produce Farm',
    commodity: 'Tomatoes',
    variety: 'Vine Ripened Regular',
    description: 'Grade A vine ripened tomatoes ready for wholesale collection.',
    expectedGrade: 'Grade A',
    estimatedQuantity: 1500,
    unit: 'kg',
    minimumQuantity: 50,
    expectedHarvestDate: '2026-08-12',
    availableFrom: '2026-08-13',
    availableUntil: '2026-08-25',
    expectedShelfLifeDays: 14,
    growingMethod: 'Drip Irrigated Field',
    packagingType: 'Standard Reusable Plastic Crates (20kg)',
    preferredCollectionMethod: 'AgriTrust Logistics Pickup',
    additionalNotes: 'Brix reading expected > 9.0°Bx.',
    status: 'UNDER_REVIEW',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80'],
    documents: ['/docs/phyto_cert_SUP-2026-000001.pdf'],
    location: {
      region: 'Western Agricultural Zone 4',
      privateGpsLat: 13.1932,
      privateGpsLng: -59.5432,
    },
    aiRecommendation: {
      suggestedGrade: 'Grade A',
      suggestedPrice: 2.40,
      suggestedMoq: 50,
      confidence: 97.5,
    },
    createdAt: '2026-08-10T07:30:00Z',
    updatedAt: '2026-08-10T07:30:00Z',
  },
  {
    id: 'SUP-2026-000002',
    sellerId: 'fp-01',
    sellerName: 'Green Valley Produce Farm',
    commodity: 'Lettuce',
    variety: 'Romaine Heart Crisp',
    description: 'Hydro-cooled Romaine hearts packed in wholesale crates.',
    expectedGrade: 'Grade A',
    estimatedQuantity: 400,
    unit: 'crate',
    minimumQuantity: 10,
    expectedHarvestDate: '2026-08-13',
    availableFrom: '2026-08-14',
    availableUntil: '2026-08-22',
    expectedShelfLifeDays: 10,
    growingMethod: 'Protected Shadehouse',
    packagingType: 'Ventilated Cardboard Wholesale Crates',
    preferredCollectionMethod: 'AgriTrust Logistics Pickup',
    additionalNotes: 'Hydro-cooled immediately post harvest.',
    status: 'SUBMITTED',
    images: ['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=800&q=80'],
    documents: [],
    location: {
      region: 'Western Agricultural Zone 4',
      privateGpsLat: 13.1932,
      privateGpsLng: -59.5432,
    },
    aiRecommendation: {
      suggestedGrade: 'Grade A',
      suggestedPrice: 34.50,
      suggestedMoq: 10,
      confidence: 96.0,
    },
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-08-10T08:00:00Z',
  },
];

export const SEED_LOTS: Lot[] = [
  {
    id: 'AT-LOT-2026-000922',
    productId: 'prod-01',
    harvestId: 'harv-101',
    farmerId: 'fp-01',
    cropName: 'Tomatoes',
    varietyName: 'Vine Ripened Regular',
    commodity: 'Tomatoes',
    variety: 'Vine Ripened Regular',
    description: 'Freshly harvested Grade A wholesale tomatoes. Deep crimson colour, firm texture, optimal acidity balance for commercial culinary applications.',
    harvestDate: '2026-08-08',
    grade: 'Grade A',
    availableStock: 1200,
    initialQuantityKg: 1500,
    availableQuantityKg: 1200,
    unit: 'kg',
    moq: 50,
    moqUnit: 'kg',
    wholesalePrice: 2.40,
    currency: 'USD',
    productImage: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    additionalImages: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80'],
    availability: true,
    traceabilityStatus: 'VERIFIED',
    qualityStatus: 'PASSED',
    procurementStatus: 'AVAILABLE',
    status: 'VERIFIED',
    publicationStatus: 'HIDDEN',
    publicVisibility: false,
    createdAt: '2026-08-08T06:00:00Z',
    updatedAt: '2026-08-08T06:00:00Z',
    internalNotes: 'Optimal Brix reading 9.2°Bx. Prime candidate for immediate distribution.',
    verificationHash: 'vhash_9922_a87f12',
    publicRegion: 'Western Agricultural Zone 4',
  },
  {
    id: 'AT-LOT-2026-000923',
    productId: 'prod-02',
    harvestId: 'harv-102',
    farmerId: 'fp-01',
    cropName: 'Tomatoes',
    varietyName: 'Plum Roma',
    commodity: 'Tomatoes',
    variety: 'Plum Roma',
    description: 'High-density Roma tomatoes tailored for hospitality, sauce production, and commercial processing. Excellent post-harvest stability.',
    harvestDate: '2026-08-07',
    grade: 'Grade A',
    availableStock: 850,
    initialQuantityKg: 1000,
    availableQuantityKg: 850,
    unit: 'kg',
    moq: 40,
    moqUnit: 'kg',
    wholesalePrice: 2.80,
    currency: 'USD',
    productImage: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?auto=format&fit=crop&w=800&q=80',
    availability: true,
    traceabilityStatus: 'VERIFIED',
    qualityStatus: 'PASSED',
    procurementStatus: 'AVAILABLE',
    status: 'VERIFIED',
    publicationStatus: 'HIDDEN',
    publicVisibility: false,
    createdAt: '2026-08-07T06:00:00Z',
    updatedAt: '2026-08-07T06:00:00Z',
    internalNotes: 'Targeted for hotel food processing clients.',
    verificationHash: 'vhash_9923_b44c31',
    publicRegion: 'Western Agricultural Zone 4',
  },
  {
    id: 'AT-LOT-2026-000924',
    productId: 'prod-03',
    harvestId: 'harv-103',
    farmerId: 'fp-01',
    cropName: 'Lettuce',
    varietyName: 'Romaine Heart Crisp',
    commodity: 'Lettuce',
    variety: 'Romaine Heart Crisp',
    description: 'Hydro-cooled Romaine lettuce heads packed in standard wholesale ventilation crates. High leaf density and vibrant green colour.',
    harvestDate: '2026-08-09',
    grade: 'Grade A',
    availableStock: 400,
    initialQuantityKg: 600,
    availableQuantityKg: 400,
    unit: 'crate',
    moq: 10,
    moqUnit: 'crate',
    wholesalePrice: 34.50,
    currency: 'USD',
    productImage: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=800&q=80',
    availability: true,
    traceabilityStatus: 'VERIFIED',
    qualityStatus: 'PASSED',
    procurementStatus: 'AVAILABLE',
    status: 'VERIFIED',
    publicationStatus: 'HIDDEN',
    publicVisibility: false,
    createdAt: '2026-08-09T05:30:00Z',
    updatedAt: '2026-08-09T05:30:00Z',
    internalNotes: 'Hydro-cooled pre-shipment complete.',
    verificationHash: 'vhash_9924_c99e45',
    publicRegion: 'Western Agricultural Zone 4',
  },
  {
    id: 'AT-LOT-2026-000925',
    productId: 'prod-04',
    harvestId: 'harv-104',
    farmerId: 'fp-01',
    cropName: 'Cucumbers',
    varietyName: 'English Seedless',
    commodity: 'Cucumbers',
    variety: 'English Seedless',
    description: 'Uniformly graded English cucumbers wrapped for maximum freshness. Crisp bite, dark green skin, ideal for premium foodservice buyers.',
    harvestDate: '2026-08-08',
    grade: 'Grade A',
    availableStock: 1500,
    initialQuantityKg: 1800,
    availableQuantityKg: 1500,
    unit: 'kg',
    moq: 60,
    moqUnit: 'kg',
    wholesalePrice: 1.90,
    currency: 'USD',
    productImage: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=800&q=80',
    availability: true,
    traceabilityStatus: 'VERIFIED',
    qualityStatus: 'PASSED',
    procurementStatus: 'AVAILABLE',
    status: 'VERIFIED',
    publicationStatus: 'HIDDEN',
    publicVisibility: false,
    createdAt: '2026-08-08T07:00:00Z',
    updatedAt: '2026-08-08T07:00:00Z',
    internalNotes: 'Individually film-wrapped for shelf life extension.',
    verificationHash: 'vhash_9925_d11a88',
    publicRegion: 'Western Agricultural Zone 4',
  },
  {
    id: 'AT-LOT-2026-000926',
    productId: 'prod-05',
    harvestId: 'harv-105',
    farmerId: 'fp-01',
    cropName: 'Sweet Peppers',
    varietyName: 'Bell Trio (Red/Yellow/Green)',
    commodity: 'Peppers',
    variety: 'Bell Trio',
    description: 'Thick-walled Grade A bell peppers in balanced colour ratios of red, yellow and green. High vitamin C content and vibrant skin finish.',
    harvestDate: '2026-08-06',
    grade: 'Grade A',
    availableStock: 600,
    initialQuantityKg: 800,
    availableQuantityKg: 600,
    unit: 'kg',
    moq: 30,
    moqUnit: 'kg',
    wholesalePrice: 4.20,
    currency: 'USD',
    productImage: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    availability: true,
    traceabilityStatus: 'VERIFIED',
    qualityStatus: 'PASSED',
    procurementStatus: 'AVAILABLE',
    status: 'VERIFIED',
    publicationStatus: 'PUBLISHED',
    publishedAt: '2026-08-06T08:00:00Z',
    publishedBy: 'sys-admin',
    publicVisibility: true,
    createdAt: '2026-08-06T08:00:00Z',
    updatedAt: '2026-08-06T08:00:00Z',
    internalNotes: 'Tri-color 1:1:1 mix pre-sorted in crates.',
    verificationHash: 'vhash_9926_e55f99',
    publicRegion: 'Western Agricultural Zone 4',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    lotId: 'AT-LOT-2026-000922',
    name: 'Vine-Ripened Regular Tomatoes',
    variety: 'Vine Ripened Regular',
    category: 'Tomatoes',
    description: 'Freshly harvested Grade A wholesale tomatoes. Deep crimson color, firm texture, optimal acidity balance for commercial culinary applications.',
    unit: 'kg',
    unitWeightKg: 1,
    pricePerUnit: 2.40,
    moqUnits: 50,
    availableUnits: 1200,
    grade: 'Grade A',
    availabilityStatus: 'IN_STOCK',
    harvestDate: '2026-08-08',
    publicRegion: 'Western Agricultural Zone 4',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    createdAt: '2026-08-08T09:00:00Z',
  },
  {
    id: 'prod-02',
    lotId: 'AT-LOT-2026-000923',
    name: 'Plum Roma Tomatoes',
    variety: 'Plum Roma',
    category: 'Tomatoes',
    description: 'High-density Roma tomatoes tailored for hospitality, sauce production, and commercial processing. Excellent post-harvest stability.',
    unit: 'kg',
    unitWeightKg: 1,
    pricePerUnit: 2.80,
    moqUnits: 40,
    availableUnits: 850,
    grade: 'Grade A',
    availabilityStatus: 'IN_STOCK',
    harvestDate: '2026-08-07',
    publicRegion: 'Western Agricultural Zone 4',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    createdAt: '2026-08-07T09:00:00Z',
  },
  {
    id: 'prod-03',
    lotId: 'AT-LOT-2026-000924',
    name: 'Crisp Romaine Lettuce Crates',
    variety: 'Romaine Heart Crisp',
    category: 'Lettuce',
    description: 'Hydro-cooled Romaine lettuce heads packed in standard wholesale ventilation crates. High leaf density and vibrant green color.',
    unit: 'crate',
    unitWeightKg: 12,
    pricePerUnit: 34.50,
    moqUnits: 10,
    availableUnits: 400,
    grade: 'Grade A',
    availabilityStatus: 'IN_STOCK',
    harvestDate: '2026-08-09',
    publicRegion: 'Western Agricultural Zone 4',
    imageUrl: 'https://images.unsplash.com/photo-1556801712-76c8eb07ebd1?auto=format&fit=crop&w=800&q=80',
    createdAt: '2026-08-09T09:00:00Z',
  },
  {
    id: 'prod-04',
    lotId: 'AT-LOT-2026-000925',
    name: 'English Seedless Cucumbers',
    variety: 'English Seedless',
    category: 'Cucumbers',
    description: 'Uniformly graded English cucumbers wrapped for maximum freshness. Crisp bite, dark green skin, ideal for premium foodservice buyers.',
    unit: 'kg',
    unitWeightKg: 1,
    pricePerUnit: 1.90,
    moqUnits: 60,
    availableUnits: 1500,
    grade: 'Grade A',
    availabilityStatus: 'IN_STOCK',
    harvestDate: '2026-08-08',
    publicRegion: 'Western Agricultural Zone 4',
    imageUrl: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=800&q=80',
    createdAt: '2026-08-08T09:30:00Z',
  },
  {
    id: 'prod-05',
    lotId: 'AT-LOT-2026-000926',
    name: 'Sweet Bell Peppers (Trio Pack)',
    variety: 'Bell Trio',
    category: 'Peppers',
    description: 'Thick-walled Grade A bell peppers in balanced color ratios (Red, Yellow, Green). High vitamin C content, vibrant skin finish.',
    unit: 'kg',
    unitWeightKg: 1,
    pricePerUnit: 4.20,
    moqUnits: 30,
    availableUnits: 600,
    grade: 'Grade A',
    availabilityStatus: 'IN_STOCK',
    harvestDate: '2026-08-06',
    publicRegion: 'Western Agricultural Zone 4',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    createdAt: '2026-08-06T10:00:00Z',
  },
];

export const SEED_LOT_EVENTS: Record<string, LotEvent[]> = {
  'AT-LOT-2026-000922': [
    {
      id: 'le-101',
      lotId: 'AT-LOT-2026-000922',
      eventType: 'HARVESTED',
      timestamp: '2026-08-08T06:00:00Z',
      locationSummary: 'Western Agricultural Zone 4 (Harvest Hub A)',
      notes: 'Hand-picked under controlled temperature window.',
    },
    {
      id: 'le-102',
      lotId: 'AT-LOT-2026-000922',
      eventType: 'GRADED',
      timestamp: '2026-08-08T08:15:00Z',
      locationSummary: 'AgriTrust Intake Facility #2',
      notes: 'AI Spectrovision analysis + human inspector sign-off. Assigned Grade A.',
    },
    {
      id: 'le-103',
      lotId: 'AT-LOT-2026-000922',
      eventType: 'VERIFIED',
      timestamp: '2026-08-08T08:30:00Z',
      locationSummary: 'AgriTrust Core Ledger',
      notes: 'Cryptographic hash generated. Ready for wholesale allocation.',
    },
  ],
};

export const SEED_LOT_QUALITY: Record<string, LotQuality> = {
  'AT-LOT-2026-000922': {
    id: 'lq-9922',
    lotId: 'AT-LOT-2026-000922',
    grade: 'Grade A',
    aiConfidenceScore: 98.4,
    inspectorId: 'insp-042',
    inspectionDate: '2026-08-08T08:15:00Z',
    defectsDetected: ['Minor surface color variance (<1.2%)'],
    status: 'ACCEPTED',
  },
};

export const SEED_LOT_DOCUMENTS: Record<string, LotDocument[]> = {
  'AT-LOT-2026-000922': [
    {
      id: 'ld-doc-1',
      lotId: 'AT-LOT-2026-000922',
      documentType: 'QUALITY_CERT',
      fileUrl: '/docs/quality_cert_9922.pdf',
      fileHash: 'sha256_qc_9922_88a91c',
      uploadedAt: '2026-08-08T08:20:00Z',
    },
    {
      id: 'ld-doc-2',
      lotId: 'AT-LOT-2026-000922',
      documentType: 'PHYTOSANITARY',
      fileUrl: '/docs/phyto_cert_9922.pdf',
      fileHash: 'sha256_phyto_9922_c77e01',
      uploadedAt: '2026-08-08T08:22:00Z',
    },
    {
      id: 'ld-doc-3',
      lotId: 'AT-LOT-2026-000922',
      documentType: 'LAB_TEST',
      fileUrl: '/docs/lab_analysis_9922.pdf',
      fileHash: 'sha256_lab_9922_f44d89',
      uploadedAt: '2026-08-08T08:25:00Z',
    },
  ],
};

export const SEED_BUYER_ORDERS: Order[] = [
  {
    id: 'ORD-2026-000881',
    buyerId: 'bp-01',
    items: [
      {
        productId: 'prod-01',
        productName: 'Vine-Ripened Regular Tomatoes',
        lotId: 'AT-LOT-2026-000922',
        unit: 'kg',
        unitPrice: 2.40,
        quantity: 300,
        subtotal: 720.00,
      },
      {
        productId: 'prod-04',
        productName: 'English Seedless Cucumbers',
        lotId: 'AT-LOT-2026-000925',
        unit: 'kg',
        unitPrice: 1.90,
        quantity: 200,
        subtotal: 380.00,
      },
    ],
    subtotal: 1100.00,
    logisticsFee: 45.00,
    platformFee: 27.50,
    tax: 0.00,
    total: 1172.50,
    status: 'DISPATCHED',
    createdAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'ORD-2026-000750',
    buyerId: 'bp-01',
    items: [
      {
        productId: 'prod-03',
        productName: 'Crisp Romaine Lettuce Crates',
        lotId: 'AT-LOT-2026-000924',
        unit: 'crate',
        unitPrice: 34.50,
        quantity: 20,
        subtotal: 690.00,
      },
    ],
    subtotal: 690.00,
    logisticsFee: 45.00,
    platformFee: 17.25,
    tax: 0.00,
    total: 752.25,
    status: 'DELIVERED',
    createdAt: '2026-08-05T14:30:00Z',
  },
];

export const SEED_BUYER_LOGISTICS: Array<{ order: LogisticsOrder; shipment: Shipment }> = [
  {
    order: {
      id: 'log-881',
      orderId: 'ORD-2026-000881',
      carrierName: 'AgriTrust Cold Express Line 4',
      vehicleType: 'Refrigerated 10-Ton Truck (Temp: 13.0°C)',
      originHub: 'Intake Facility #2 (Western Zone)',
      destinationHub: 'Island Fresh Central Distribution Hub',
      estArrival: '2026-08-10T16:00:00Z',
      status: 'IN_TRANSIT',
    },
    shipment: {
      id: 'ship-881',
      logisticsOrderId: 'log-881',
      trackingCode: 'AT-SHIP-881-8849',
      currentPublicLocation: 'En route via Highway 1 (Sector B)',
      updatedAt: '2026-08-10T04:00:00Z',
    },
  },
];

export const SEED_BUYER_INVOICES: Invoice[] = [
  {
    id: 'inv-881',
    orderId: 'ORD-2026-000881',
    invoiceNumber: 'INV-2026-000881',
    amount: 1172.50,
    status: 'PAID',
    issuedAt: '2026-08-08T10:05:00Z',
    dueAt: '2026-08-22T10:05:00Z',
  },
  {
    id: 'inv-750',
    orderId: 'ORD-2026-000750',
    invoiceNumber: 'INV-2026-000750',
    amount: 752.25,
    status: 'PAID',
    issuedAt: '2026-08-05T14:35:00Z',
    dueAt: '2026-08-19T14:35:00Z',
  },
];

export const SEED_BUYER_PROCUREMENT_REQUESTS: ProcurementRequest[] = [
  {
    id: 'pr-01',
    buyerId: 'bp-01',
    cropName: 'Tomatoes (Plum Roma)',
    quantityKg: 500,
    requiredDeliveryDate: '2026-08-15',
    maxPricePerKg: 2.85,
    status: 'MATCHED',
  },
  {
    id: 'pr-02',
    buyerId: 'bp-01',
    cropName: 'Sweet Bell Peppers',
    quantityKg: 300,
    requiredDeliveryDate: '2026-08-18',
    maxPricePerKg: 4.30,
    status: 'OPEN',
  },
];

export const SEED_FARMER_SETTLEMENTS: Settlement[] = [
  {
    id: 'set-9922',
    farmerId: 'fp-01',
    lotId: 'AT-LOT-2026-000922',
    cropName: 'Vine-Ripened Regular Tomatoes',
    totalUnitsKg: 500,
    grossAmount: 1200.00,
    platformDeduction: 60.00,
    netPayout: 1140.00,
    status: 'SETTLED',
    payoutDate: '2026-08-09T14:00:00Z',
  },
  {
    id: 'set-9923',
    farmerId: 'fp-01',
    lotId: 'AT-LOT-2026-000923',
    cropName: 'Hydroponic Butterhead Lettuce',
    totalUnitsKg: 300,
    grossAmount: 850.00,
    platformDeduction: 42.50,
    netPayout: 807.50,
    status: 'ESCROW_HELD',
    payoutDate: '2026-08-12T12:00:00Z',
  },
];

export const SEED_CMS_CONTENT = {
  headline: 'Wholesale Produce. Ready for Business.',
  heroTitle: 'Wholesale Produce. Ready for Business.',
  heroSubtitle: 'Fresh agricultural products available in bulk for hotels, restaurants, retailers, distributors and commercial buyers.',
  ctaText: 'BUY NOW',
  heroImage: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=1200&q=80',
  featuredLotIds: ['AT-LOT-2026-000926'],
  trustMessaging: 'Direct B2B Procurement & Fulfilment.',
  traceabilityMessaging: 'Verified Agricultural Provenance.',
  footerContent: 'AgriTrust B2B Wholesale Commerce Platform',
  updatedAt: new Date().toISOString(),
};

export const SEED_LANDING_PAGE_BLOCKS: CMSPageBlock[] = [
  {
    id: 'block-hero-01',
    type: 'HERO',
    title: 'Wholesale Produce. Ready for Business.',
    subtitle: 'Fresh agricultural products available in bulk for hotels, restaurants, retailers, distributors and commercial buyers.',
    displayOrder: 1,
    settings: {
      visible: true,
      bgStyle: 'surface',
      alignment: 'left',
      primaryButtonText: 'BUY NOW',
      primaryButtonLink: '#marketplace',
      secondaryButtonText: 'BECOME A BUYER',
      secondaryButtonLink: '#buyer-onboarding',
      textLinkText: 'SELL YOUR PRODUCE',
      textLinkLink: '#seller-onboarding',
      imageUrl: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=1200&q=80',
    },
  },
  {
    id: 'block-grid-02',
    type: 'PRODUCT_GRID',
    title: 'Fresh Produce. Ready for Wholesale.',
    subtitle: 'Browse currently available produce from the AgriTrust wholesale marketplace and find the products your business needs.',
    displayOrder: 2,
    settings: {
      visible: true,
      bgStyle: 'light',
      alignment: 'center',
      dataSource: 'PUBLISHED_INVENTORY',
      limit: 8,
      primaryButtonText: 'Browse Wholesale Catalog',
    },
  },
  {
    id: 'block-intermediary-03',
    type: 'CONTROLLED_INTERMEDIARY',
    title: 'How AgriTrust Secures Wholesale Agriculture',
    subtitle: 'AgriTrust brings supply, quality, pricing, logistics, and fulfilment together through one coordinated wholesale platform. Businesses get a simpler way to source fresh agricultural produce while AgriTrust manages the complexity behind every transaction.',
    displayOrder: 3,
    content: {
      eyebrow: 'Controlled Intermediary Model',
      benefits: [
        {
          title: 'Quality Controlled',
          description: "Produce is assessed through AgriTrust's quality processes before entering the wholesale marketplace.",
          icon: 'ShieldCheck'
        },
        {
          title: 'Supply Coordinated',
          description: 'We coordinate agricultural supply to help businesses access the products and quantities they need.',
          icon: 'Layers'
        },
        {
          title: 'Wholesale Focused',
          description: 'Our marketplace is designed around commercial purchasing, bulk quantities, minimum order requirements, and wholesale pricing.',
          icon: 'ShoppingBag'
        },
        {
          title: 'Fulfilment Managed',
          description: 'AgriTrust coordinates the movement of produce from supply through delivery so buyers have one platform to manage their procurement.',
          icon: 'Truck'
        },
        {
          title: 'Traceable',
          description: 'Every eligible lot maintains a structured traceability record throughout its journey.',
          icon: 'FileCheck'
        }
      ]
    },
    settings: {
      visible: true,
      bgStyle: 'surface',
      alignment: 'left',
      imageUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=800&q=80',
    },
  },
  {
    id: 'block-newsletter-04',
    type: 'NEWSLETTER_SUBSCRIBE',
    title: 'Stay Connected to the AgriTrust Market',
    subtitle: 'Get wholesale availability, new products, market updates and opportunities delivered directly to your inbox.',
    displayOrder: 4,
    content: {
      eyebrow: 'AgriTrust Market Intelligence',
      supportingCopy: 'Be the first to hear about new wholesale produce, market opportunities, seasonal availability and updates from AgriTrust.',
    },
    settings: {
      visible: true,
      bgStyle: 'surface',
      alignment: 'center',
    },
  },
  {
    id: 'block-categories-05',
    type: 'CATEGORIES',
    title: 'Browse Commercial Produce Categories',
    subtitle: 'High-grade fresh produce categorized for hospitality & retail procurement.',
    displayOrder: 4,
    settings: {
      visible: true,
      bgStyle: 'surface',
      alignment: 'center',
    },
  },
  {
    id: 'block-howitworks-04',
    type: 'HOW_IT_WORKS',
    title: 'How AgriTrust Wholesale Sourcing Works',
    subtitle: 'Streamlined commercial B2B procurement in 3 simple steps.',
    displayOrder: 4,
    settings: {
      visible: true,
      bgStyle: 'glass',
      alignment: 'center',
    },
  },
  {
    id: 'block-cta-05',
    type: 'CTA_SECTION',
    title: 'Supply Your Harvest to AgriTrust Wholesale',
    subtitle: 'Connect your agricultural production directly with premier commercial buyers across the Caribbean region.',
    displayOrder: 5,
    settings: {
      visible: true,
      bgStyle: 'brand',
      alignment: 'center',
      primaryButtonText: 'Sell Your Produce',
      primaryButtonLink: '#seller-onboarding',
      secondaryButtonText: 'Become a Buyer',
      secondaryButtonLink: '#buyer-onboarding',
    },
  },
  {
    id: 'block-faq-06',
    type: 'FAQ',
    title: 'Frequently Asked Sourcing Questions',
    subtitle: 'Everything you need to know about commercial ordering, delivery, and payment terms.',
    displayOrder: 6,
    settings: {
      visible: true,
      bgStyle: 'surface',
      alignment: 'center',
    },
  },
];

export const SEED_SEO_CONFIG: CMSSEOConfig = {
  pageTitle: 'AgriTrust — B2B Wholesale Agricultural Marketplace',
  metaDescription: 'Fresh agricultural produce available in bulk for hotels, restaurants, supermarkets, and commercial distributors.',
  canonicalUrl: 'https://agritrust.com/',
  ogTitle: 'AgriTrust Wholesale Produce Sourcing',
  ogDescription: 'Buy fresh Grade A agricultural produce directly at commercial wholesale scale.',
  ogImage: 'https://images.unsplash.com/photo-1595855759920-86582396756a',
  robots: 'index, follow',
};

export const SEED_NAVIGATION_ITEMS: CMSNavigationItem[] = [
  { id: 'nav-01', label: 'Home', path: '/', displayOrder: 1, visible: true },
  { id: 'nav-02', label: 'Shop Produce', path: '#marketplace', displayOrder: 2, visible: true },
  { id: 'nav-03', label: 'Categories', path: '#categories', displayOrder: 3, visible: true },
  { id: 'nav-04', label: 'How It Works', path: '#how-it-works', displayOrder: 4, visible: true },
  { id: 'nav-05', label: 'Sell Your Produce', path: '#seller-onboarding', displayOrder: 5, visible: true },
  { id: 'nav-06', label: 'Become a Buyer', path: '#buyer-onboarding', displayOrder: 6, visible: true },
];

export const SEED_FOOTER_CONFIG: CMSFooterConfig = {
  companyDescription: 'AgriTrust is the premier Caribbean B2B agricultural commerce platform, delivering reliable wholesale produce sourcing, quality grading, and fulfilled delivery.',
  columns: [
    {
      title: 'Wholesale Commerce',
      links: [
        { label: 'Browse Products', url: '#marketplace' },
        { label: 'Become a Buyer', url: '#buyer-onboarding' },
        { label: 'Sell Your Produce', url: '#seller-onboarding' },
        { label: 'Credit Terms', url: '#terms' },
      ],
    },
    {
      title: 'Platform Capabilities',
      links: [
        { label: 'Quality Standards', url: '#quality' },
        { label: 'Traceability Ledger', url: '#traceability' },
        { label: 'Logistics Network', url: '#logistics' },
      ],
    },
    {
      title: 'Legal & Compliance',
      links: [
        { label: 'Privacy Policy', url: '#privacy' },
        { label: 'Terms of Service', url: '#terms' },
        { label: 'Phytosanitary Protocol', url: '#phyto' },
      ],
    },
  ],
  copyrightText: `© ${new Date().getFullYear()} AgriTrust B2B Platform Core. All rights reserved.`,
  privacyPolicyUrl: '#privacy',
  termsUrl: '#terms',
};

export const SEED_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'media-01',
    filename: 'hero_agricultural_field.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=1200&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 245100,
    dimensions: { width: 1200, height: 800 },
    uploadedBy: 'sys-admin',
    uploadedAt: '2026-08-01T10:00:00Z',
    usedIn: ['Landing Page Hero'],
    hash: 'hash_img_01_hero',
  },
  {
    id: 'media-02',
    filename: 'fresh_tomatoes_wholesale.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 184200,
    dimensions: { width: 800, height: 600 },
    uploadedBy: 'sys-admin',
    uploadedAt: '2026-08-02T11:00:00Z',
    usedIn: ['Tomatoes Product', 'Available Now Section'],
    hash: 'hash_img_02_tomatoes',
  },
  {
    id: 'media-03',
    filename: 'romaine_lettuce_crates.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=800&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 162900,
    dimensions: { width: 800, height: 600 },
    uploadedBy: 'sys-admin',
    uploadedAt: '2026-08-02T11:30:00Z',
    usedIn: ['Lettuce Product', 'Available Now Section'],
    hash: 'hash_img_03_lettuce',
  },
];

export const SEED_AI_AGENTS = [
  {
    id: 'agent-spectro-01',
    name: 'Spectrovision Grading Agent',
    version: 'v4.2',
    status: 'ACTIVE' as const,
    owner: 'insp-042',
    purpose: 'Spectral wavelength reflectance analysis and AI produce grading recommendation',
    allowedCapabilities: ['READ_LOT', 'READ_INSPECTION_DATA', 'ANALYSE_IMAGE', 'ANALYSE_SPECTRAL_DATA', 'WRITE_AI_RECOMMENDATION'],
    allowedTools: ['spectrometer_scanner', 'brix_evaluator', 'color_analyzer'],
    riskLevel: 'MEDIUM' as const,
    lastActivity: '2026-08-10T04:15:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-procure-02',
    name: 'Procurement Allocation Agent',
    version: 'v2.1',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Automated matching of buyer procurement requests with available seller harvest lots',
    allowedCapabilities: ['READ_LOT', 'READ_PROCUREMENT_REQUEST', 'SUGGEST_MATCH'],
    allowedTools: ['demand_matcher', 'capacity_checker'],
    riskLevel: 'MEDIUM' as const,
    lastActivity: '2026-08-10T03:50:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-pricing-03',
    name: 'Pricing Intelligence Agent',
    version: 'v3.0',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Minimum Margin Protection Engine compliance and landed cost pricing analysis',
    allowedCapabilities: ['READ_COST_BREAKDOWN', 'EVALUATE_MARGIN'],
    allowedTools: ['margin_calculator', 'cost_evaluator'],
    riskLevel: 'HIGH' as const,
    lastActivity: '2026-08-10T04:00:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-demand-04',
    name: 'Demand Forecast Agent',
    version: 'v1.8',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Regional commodity demand trend prediction for buyers and producers',
    allowedCapabilities: ['READ_MARKET_TRENDS', 'GENERATE_FORECAST'],
    allowedTools: ['trend_analyzer'],
    riskLevel: 'LOW' as const,
    lastActivity: '2026-08-09T22:10:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-logistics-05',
    name: 'Logistics Optimisation Agent',
    version: 'v2.4',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Cold-chain delivery route optimization and temperature log anomaly detection',
    allowedCapabilities: ['READ_SHIPMENT', 'ANALYSE_TEMP_LOGS'],
    allowedTools: ['route_optimizer', 'temp_monitor'],
    riskLevel: 'LOW' as const,
    lastActivity: '2026-08-10T04:20:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-doc-06',
    name: 'Document Intelligence Agent',
    version: 'v1.5',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Phytosanitary & business license OCR validation and security sanitization',
    allowedCapabilities: ['READ_DOCUMENT', 'SANITIZE_PROMPT_INJECTION', 'VERIFY_MAGIC_BYTES'],
    allowedTools: ['file_security_pipeline'],
    riskLevel: 'MEDIUM' as const,
    lastActivity: '2026-08-10T02:00:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
  {
    id: 'agent-risk-07',
    name: 'Risk Detection Agent',
    version: 'v1.2',
    status: 'ACTIVE' as const,
    owner: 'sys-admin',
    purpose: 'Real-time security threat detection and Two-Human sign-off policy trigger',
    allowedCapabilities: ['READ_AUDIT_LOG', 'TRIGGER_APPROVAL_REQUEST'],
    allowedTools: ['security_vault_inspector'],
    riskLevel: 'HIGH' as const,
    lastActivity: '2026-08-10T04:30:00Z',
    currentPolicy: 'GOV-POL-2026-V1',
  },
];

export const SEED_AI_RUNS = [
  {
    id: 'run-9922-01',
    agentId: 'agent-spectro-01',
    agentName: 'Spectrovision Grading Agent',
    timestamp: '2026-08-08T08:15:00Z',
    requestedAction: 'GRADE_RECOMMENDATION',
    inputEntity: 'AT-LOT-2026-000922',
    outputSummary: 'Recommended Grade A (Brix 9.2°Bx, RGB Uniformity 99.2%, Defects 0.35%)',
    confidence: 98.4,
    riskLevel: 'LOW' as const,
    policyResult: 'PASSED' as const,
    humanApprovalRequired: false,
    approvalStatus: 'NOT_REQUIRED' as const,
    executionStatus: 'COMPLETED' as const,
  },
  {
    id: 'run-override-02',
    agentId: 'agent-spectro-01',
    agentName: 'Spectrovision Grading Agent',
    timestamp: '2026-08-10T04:15:00Z',
    requestedAction: 'GRADE_OVERRIDE_REQUEST',
    inputEntity: 'AT-LOT-2026-000922',
    outputSummary: 'Manual inspector override request from Grade B to Grade A',
    confidence: 98.4,
    riskLevel: 'HIGH' as const,
    policyResult: 'FLAGGED' as const,
    humanApprovalRequired: true,
    approvalStatus: 'APPROVED' as const,
    executionStatus: 'COMPLETED' as const,
  },
];

export const SEED_ADMIN_PROFILE: AdminProfile = {
  id: 'admin-prof-01',
  actorId: 'usr-admin-sys-001', // Immutable user ID for audit trailing
  photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  firstName: 'Alexander',
  lastName: 'Vance',
  displayName: 'Alex Vance (Chief Admin)',
  username: 'avance.admin',
  email: 'admin@agritrust.example',
  emailVerified: true,
  phone: '+1 (246) 555-0199',
  jobTitle: 'VP of Platform Operations',
  department: 'Executive Operations',
  preferredLanguage: 'English (US)',
  timeZone: 'America/Barbados',
  preferences: {
    language: 'English (US)',
    timeZone: 'America/Barbados',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '24h',
    notifyEmail: true,
    notifyInApp: true,
    defaultDashboardView: 'OVERVIEW',
  },
};

export const SEED_FEATURE_FLAGS_LIST: FeatureFlagSetting[] = [
  { id: 'ff-01', name: 'Buyer Registration', key: 'BUYER_REGISTRATION', description: 'Allows new commercial buyers to submit onboarding applications.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-02', name: 'Seller Registration', key: 'SELLER_REGISTRATION', description: 'Allows agricultural producers to submit supply intake requests.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-03', name: 'Wholesale Marketplace', key: 'WHOLESALE_MARKETPLACE', description: 'Public wholesale produce catalog and lot exploration.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-04', name: 'Cart & Purchasing', key: 'CART', description: 'B2B shopping cart and lot reservation engine.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-05', name: 'Checkout & Settlement', key: 'CHECKOUT', description: 'Commercial order placement and escrow payment checkout.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-06', name: 'Google OAuth Sign-In', key: 'GOOGLE_LOGIN', description: 'Single Sign-On authentication via Google Workspace.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-07', name: 'Apple ID Sign-In', key: 'APPLE_LOGIN', description: 'Single Sign-On authentication via Apple ID.', status: 'DISABLED', targetAudience: 'INTERNAL_TESTERS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-08', name: 'Public Traceability Ledger', key: 'PUBLIC_TRACEABILITY', description: 'Public QR verification and deep blockchain traceability view.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-09', name: 'AI Produce Grading', key: 'AI_GRADING', description: 'Spectrovision wavelength automated quality grading recommendations.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-10', name: 'AI Dynamic Pricing', key: 'AI_PRICING', description: 'Automated landed cost calculation and margin target validation.', status: 'ENABLED', targetAudience: 'ADMINS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-11', name: 'Cold-Chain Route Optimisation', key: 'ROUTE_OPTIMIZATION', description: 'Logistics delivery route calculation and GPS tracking.', status: 'BETA', targetAudience: 'INTERNAL_TESTERS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-12', name: 'Document OCR Intake', key: 'DOCUMENT_OCR', description: 'Automated phytosanitary & business license document scanning.', status: 'ENABLED', targetAudience: 'ADMINS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-13', name: 'Mobile App Features', key: 'MOBILE_FEATURES', description: 'Progressive Web App push notifications and offline field mode.', status: 'BETA', targetAudience: 'INTERNAL_TESTERS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-14', name: 'Automated Email Notifications', key: 'NOTIFICATIONS', description: 'Email alert dispatch for order status updates and security events.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-15', name: 'Invoice PDF Generation', key: 'INVOICE_GENERATION', description: 'Automated VAT/GST compliant tax invoice PDF generation.', status: 'ENABLED', targetAudience: 'ALL', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
  { id: 'ff-16', name: 'Advanced Fleet Logistics', key: 'ADVANCED_LOGISTICS', description: 'Third-party freight carrier API dispatch and temperature monitoring.', status: 'DISABLED', targetAudience: 'INTERNAL_TESTERS', updatedAt: '2026-08-10T08:00:00Z', updatedBy: 'sys-admin' },
];

export const SEED_ACTIVE_SESSIONS: ActiveSession[] = [
  { id: 'sess-01', device: 'MacBook Pro 16"', browser: 'Chrome 128.0', os: 'macOS 15.0', location: 'Bridgetown, Barbados', ipAddress: '190.107.42.18', lastActivity: '2026-08-10T10:10:00Z', createdAt: '2026-08-10T08:00:00Z', isCurrent: true },
  { id: 'sess-02', device: 'iPad Pro 12.9"', browser: 'Safari 18.0', os: 'iPadOS 18.0', location: 'Saint Michael, Barbados', ipAddress: '190.107.42.22', lastActivity: '2026-08-09T18:40:00Z', createdAt: '2026-08-08T14:20:00Z', isCurrent: false },
];

export const SEED_NOTIFICATION_ROUTINGS: NotificationRecipientRouting[] = [
  { id: 'nr-01', category: 'SECURITY', emailAddress: 'security@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'CRITICAL' },
  { id: 'nr-02', category: 'PROCUREMENT', emailAddress: 'operations@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'HIGH' },
  { id: 'nr-03', category: 'FINANCE', emailAddress: 'finance@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'HIGH' },
  { id: 'nr-04', category: 'QUALITY', emailAddress: 'quality@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'HIGH' },
  { id: 'nr-05', category: 'ORDERS', emailAddress: 'orders@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'MEDIUM' },
  { id: 'nr-06', category: 'SYSTEM', emailAddress: 'admin@agritrust.example', verificationStatus: 'VERIFIED', adminAlertEnabled: true, priority: 'HIGH' },
];

export const SEED_MARKETING_SUBSCRIBERS: MarketingSubscriber[] = [
  {
    id: 'mkt-sub-001',
    email: 'procurement@hiltonbarbados.com',
    emailNormalized: 'procurement@hiltonbarbados.com',
    audienceType: 'BUYER',
    firstName: 'Marcus',
    lastName: 'Challenor',
    source: 'landing_page',
    sourcePage: 'homepage',
    consentStatus: 'GRANTED',
    consentType: 'EXPLICIT_OPT_IN',
    consentTimestamp: '2026-08-01T09:15:00Z',
    consentVersion: 'v1.0',
    subscriptionStatus: 'SUBSCRIBED',
    createdAt: '2026-08-01T09:15:00Z',
    updatedAt: '2026-08-01T09:15:00Z',
    unsubscribeToken: 'unsub_tok_hilton_001',
    lastMarketingActivityAt: '2026-08-01T09:15:00Z',
  },
  {
    id: 'mkt-sub-002',
    email: 'farmer.joe@stluciafarms.org',
    emailNormalized: 'farmer.joe@stluciafarms.org',
    audienceType: 'FARMER',
    firstName: 'Joseph',
    lastName: 'Goddard',
    source: 'farmer_registration',
    sourcePage: 'farmer_onboarding',
    consentStatus: 'GRANTED',
    consentType: 'EXPLICIT_OPT_IN',
    consentTimestamp: '2026-08-03T11:40:00Z',
    consentVersion: 'v1.0',
    subscriptionStatus: 'SUBSCRIBED',
    createdAt: '2026-08-03T11:40:00Z',
    updatedAt: '2026-08-03T11:40:00Z',
    unsubscribeToken: 'unsub_tok_joe_002',
    lastMarketingActivityAt: '2026-08-03T11:40:00Z',
  },
  {
    id: 'mkt-sub-003',
    email: 'sarah.buyer@sandylane.com',
    emailNormalized: 'sarah.buyer@sandylane.com',
    audienceType: 'BUYER',
    firstName: 'Sarah',
    lastName: 'Williams',
    source: 'marketplace',
    sourcePage: 'catalog_view',
    consentStatus: 'GRANTED',
    consentType: 'EXPLICIT_OPT_IN',
    consentTimestamp: '2026-08-05T14:20:00Z',
    consentVersion: 'v1.0',
    subscriptionStatus: 'SUBSCRIBED',
    createdAt: '2026-08-05T14:20:00Z',
    updatedAt: '2026-08-05T14:20:00Z',
    unsubscribeToken: 'unsub_tok_sarah_003',
    lastMarketingActivityAt: '2026-08-05T14:20:00Z',
  },
  {
    id: 'mkt-sub-004',
    email: 'info@caribbeanproduce.co',
    emailNormalized: 'info@caribbeanproduce.co',
    audienceType: 'INTERESTED',
    firstName: 'David',
    lastName: 'Clarke',
    source: 'landing_page',
    sourcePage: 'homepage',
    consentStatus: 'GRANTED',
    consentType: 'EXPLICIT_OPT_IN',
    consentTimestamp: '2026-08-06T16:00:00Z',
    consentVersion: 'v1.0',
    subscriptionStatus: 'SUBSCRIBED',
    createdAt: '2026-08-06T16:00:00Z',
    updatedAt: '2026-08-06T16:00:00Z',
    unsubscribeToken: 'unsub_tok_carib_004',
    lastMarketingActivityAt: '2026-08-06T16:00:00Z',
  },
  {
    id: 'mkt-sub-005',
    email: 'unsubscribed.user@example.org',
    emailNormalized: 'unsubscribed.user@example.org',
    audienceType: 'INTERESTED',
    source: 'landing_page',
    sourcePage: 'homepage',
    consentStatus: 'WITHDRAWN',
    consentType: 'EXPLICIT_OPT_IN',
    consentTimestamp: '2026-08-02T10:00:00Z',
    consentVersion: 'v1.0',
    subscriptionStatus: 'UNSUBSCRIBED',
    createdAt: '2026-08-02T10:00:00Z',
    updatedAt: '2026-08-07T12:00:00Z',
    unsubscribedAt: '2026-08-07T12:00:00Z',
    unsubscribeToken: 'unsub_tok_old_005',
    lastMarketingActivityAt: '2026-08-07T12:00:00Z',
  },
];

/* ==========================================================================
   WHATSAPP BUSINESS AI COMMUNICATION SEED DATA (SECTION 3 & 71)
   ========================================================================== */

export const SEED_WHATSAPP_ACCOUNT: WhatsAppAccount = {
  id: 'waba-001',
  phoneNumber: 'Not Configured',
  displayBusinessName: 'AgriTrust Wholesale',
  wabaAccountId: 'Not Configured',
  status: 'NOT_CONNECTED',
  connectedAt: undefined,
  lastSyncAt: new Date().toISOString(),
  webhookUrl: '',
  webhookStatus: 'NOT_VERIFIED',
  messagesTodayCount: 0,
  activeBuyerConvsCount: 0,
  activeSellerConvsCount: 0,
  humanEscalationsCount: 0,
  aiAssistedConvsCount: 0,
  pendingApprovalsCount: 0,
  aiSystemPaused: false,
};

export const SEED_WHATSAPP_CONTACTS: WhatsAppContact[] = [
  {
    id: 'wa-cnt-001',
    whatsappId: '12465550199@c.us',
    phoneNumber: '+1 (246) 555-0199',
    name: 'Procurement Director',
    accountType: 'BUYER',
    linkedEntityId: 'buy-001',
    organisationName: 'Sandy Lane Resort Procurement',
    verifiedStatus: true,
    createdAt: '2026-08-02T10:00:00Z',
    updatedAt: '2026-08-08T14:30:00Z',
  },
  {
    id: 'wa-cnt-002',
    whatsappId: '12465550288@c.us',
    phoneNumber: '+1 (246) 555-0288',
    name: 'Co-op Operations Lead',
    accountType: 'SELLER',
    linkedEntityId: 'sel-001',
    organisationName: 'St. Philip Agricultural Co-operative',
    verifiedStatus: true,
    createdAt: '2026-08-03T11:00:00Z',
    updatedAt: '2026-08-08T15:00:00Z',
  },
];

export const SEED_WHATSAPP_CONVERSATIONS: WhatsAppConversation[] = [
  {
    id: 'wa-conv-001',
    contactId: 'wa-cnt-001',
    accountType: 'BUYER',
    linkedEntityId: 'buy-001',
    displayName: 'Sandy Lane Resort Procurement',
    status: 'AI_ACTIVE',
    aiEnabled: true,
    lastMessageText: "Hello, this is AgriTrust. I'm assisting with your wholesale produce request.",
    lastActivityAt: '2026-08-10T14:20:00Z',
    currentOrderId: 'AT-ORD-2026-0012',
    negotiationState: {
      commodityId: 'cmd-tomatoes-01',
      commodityName: 'Vine Tomatoes Grade A',
      requestedQuantityKg: 500,
      offeredPricePerKg: 2.40,
      approvedPriceFloorPerKg: 2.18,
      minimumTargetMarginPercent: 20,
      status: 'IDLE',
    },
    unreadCount: 0,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-10T14:20:00Z',
  },
  {
    id: 'wa-conv-002',
    contactId: 'wa-cnt-002',
    accountType: 'SELLER',
    linkedEntityId: 'sel-001',
    displayName: 'St. Philip Agricultural Co-operative',
    status: 'HUMAN_ACTIVE',
    aiEnabled: false,
    assignedHumanOperatorId: 'usr-admin-sys-001',
    assignedHumanOperatorName: 'Alexander Vance (VP Ops)',
    lastMessageText: 'Our operations team is currently reviewing your 800 kg harvest offer.',
    lastActivityAt: '2026-08-10T15:10:00Z',
    currentLotId: 'AT-LOT-2026-000926',
    humanTakeoverReason: 'Price exception review for high-volume harvest allocation.',
    humanTakeoverStartedAt: '2026-08-10T15:00:00Z',
    unreadCount: 1,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-10T15:10:00Z',
  },
];

export const SEED_WHATSAPP_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'wa-msg-1001',
    conversationId: 'wa-conv-001',
    direction: 'INBOUND',
    senderWhatsAppId: '12465550199@c.us',
    senderName: 'Procurement Director',
    recipientWhatsAppId: 'agritrust-system@c.us',
    text: 'Good morning, do you have 500kg of tomatoes available for delivery tomorrow?',
    timestamp: '2026-08-10T14:18:00Z',
    classification: 'AVAILABILITY',
    aiGenerated: false,
    humanApproved: false,
    deliveryStatus: 'READ',
  },
  {
    id: 'wa-msg-1002',
    conversationId: 'wa-conv-001',
    direction: 'OUTBOUND',
    senderWhatsAppId: 'agritrust-system@c.us',
    senderName: 'AgriTrust',
    recipientWhatsAppId: '12465550199@c.us',
    text: "Hello, this is AgriTrust. I'm assisting with your wholesale produce request. Yes, we currently have Grade A vine-ripened tomatoes available for wholesale purchase. For 500 kg, the current wholesale price is $2.40/kg.",
    timestamp: '2026-08-10T14:20:00Z',
    classification: 'PRICE_REQUEST',
    aiGenerated: true,
    aiAgentId: 'agent-comms-whatsapp-01',
    aiAgentVersion: 'v1.0',
    humanApproved: true,
    deliveryStatus: 'DELIVERED',
    riskLevel: 'LOW',
  },
];

export const SEED_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'wa-tpl-001',
    name: 'ORDER_CONFIRMATION',
    category: 'UTILITY',
    language: 'en_US',
    bodyText: 'Hello {{1}}, your AgriTrust wholesale order {{2}} for {{3}} kg has been confirmed. Estimated delivery: {{4}}.',
    variables: ['customer_name', 'order_id', 'quantity_kg', 'delivery_date'],
    status: 'APPROVED',
    createdAt: '2026-08-01T10:00:00Z',
    approvedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'wa-tpl-002',
    name: 'DELIVERY_UPDATE',
    category: 'UTILITY',
    language: 'en_US',
    bodyText: 'Hello {{1}}, your order {{2}} is in transit with AgriTrust Logistics. Driver status: {{3}}.',
    variables: ['customer_name', 'order_id', 'status_text'],
    status: 'APPROVED',
    createdAt: '2026-08-01T10:00:00Z',
    approvedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'wa-tpl-003',
    name: 'HUMAN_HANDOFF',
    category: 'UTILITY',
    language: 'en_US',
    bodyText: 'Hello {{1}}, I have forwarded your request to the AgriTrust Operations team for specialized review. An operator will respond shortly.',
    variables: ['customer_name'],
    status: 'APPROVED',
    createdAt: '2026-08-01T10:00:00Z',
    approvedAt: '2026-08-01T12:00:00Z',
  },
];

export const SEED_WHATSAPP_NEGOTIATION_POLICIES: WhatsAppNegotiationPolicy[] = [
  {
    commodityId: 'cmd-tomatoes-01',
    commodityName: 'Vine Tomatoes Grade A',
    baseCostPerKg: 1.70,
    currentMarketRefPrice: 2.50,
    logisticsCostPerKg: 0.15,
    processingCostPerKg: 0.05,
    operationalOverheadPerKg: 0.05,
    minimumMarginPercent: 20,
    absolutePriceFloorPerKg: 2.18,
    maxNegotiationRangePercent: 10,
  },
];

export const SEED_MARKETPLACE_SETTINGS: MarketplaceSettings = {
  minimumRequiredMarginPercent: 20, // Default 20% minimum target margin
  defaultMOQKg: 100,
  orderAutoApprovalThreshold: 5000,
  escrowHoldDays: 3,
  updatedAt: new Date().toISOString(),
  updatedByUserId: 'sys-admin',
};

